### PR TITLE
[OFFAPPS-664] updated translations

### PR DESCRIPTION
**Pull request by pmgrove**
:v:

Updated translations

/cc @zendesk/vegemite 

### References
 - Jira link: https://zendesk.atlassian.net/browse/OFFAPPS-664

### Risks
 - None

### CODE REVIEW

**Comment by pmgrove** [comment]
cc: @ydrain

**Comment by sandlerr** [comment]
:+1:

**Comment by adammw** [comment]
:+1:

**Comment by ydrain** [comment]
Thanks! cc: @injuhwang

**Pull request merged**
